baseURL = 'https://diyai.us.kg'
languageCode = 'en-us'
title = 'GoldenMagicBox'
theme = 'ananke'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 20


[deployment]
  targets = [
    {
      name = "github"
      url = "https://github.com/xd0718/xd0718.github.io.git"
      branch = "gh-pages"
    }
  ]
