baseURL = 'https://diyai.us.kg'
languageCode = 'en-us'
title = 'GoldenMagicBox'
theme = 'Dream'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 20